version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php
    restart: always
    depends_on:
      - php
  php:
    image: nanoninja/php-fpm
    container_name: mapsefficiency_app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - database
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always

  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command: install
  database:
    image: mdillon/postgis
    container_name: ${DB_HOST}
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "54321:5432"